
CREATE TABLE ESTADOS (
    ID_ESTADO INT PRIMARY KEY,
    NOME_ESTADO VARCHAR(50) NOT NULL,
    SIGLA CHAR(2) NOT NULL
);


CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_ESTADO INT,
    CONSTRAINT FK_CLIENTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);


CREATE TABLE TIPOS_TELEFONE (
    ID_TIPO_TELEFONE INT PRIMARY KEY,
    DESCRICAO_TIPO VARCHAR(50) NOT NULL
);


CREATE TABLE TELEFONES (
    ID_TELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR(20) NOT NULL,
    ID_CLIENTE INT,
    ID_TIPO_TELEFONE INT,
    CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_TELEFONE_TIPO FOREIGN KEY (ID_TIPO_TELEFONE) REFERENCES TIPOS_TELEFONE(ID_TIPO_TELEFONE)
);



SELECT C.ID_CLIENTE, C.NOME, T.NUMERO
FROM CLIENTES C
JOIN TELEFONES T ON C.ID_CLIENTE = T.ID_CLIENTE
JOIN ESTADOS E ON C.ID_ESTADO = E.ID_ESTADO
WHERE E.SIGLA = 'SP';
